### ISSUE TITLE
[Feature request] Automatic Replacement of Decimal Separator in Numeric Keypad Inputs

### ISSUE THREAD

**Issue by SunFlowerOwl** [hargata/lubelog#690] opened 2024-11-02 08:07 UTC
### Description:
I would like to request a feature that would automatically replace the decimal separator ("." or ",") in numeric inputs based on the site’s configured decimal format. Specifically, when a user enters a decimal number using the numeric keypad, the system should detect and replace the period . with the appropriate decimal separator as defined by the site's configuration, which may vary between . and ,.

### Motivation:

In many regions, the standard decimal separator differs: some use a period (.) while others use a comma (,). This can lead to input errors, especially when using the numeric keypad, which often defaults to a period (.). By implementing an automatic replacement based on the site’s settings, users can enter decimal values more accurately and efficiently without having to manually correct the separator. This feature would improve usability for international users and reduce potential data entry errors.

### Proposed Implementation:

Detect numeric input fields where decimals are allowed.
Intercept the input from the numeric keypad and, if a period . is entered, replace it with the configured decimal separator (. or ,) as specified by the site’s localization settings.
Ensure that this replacement is seamless and does not disrupt the user experience, ideally by handling the change in the background.

### Additional Notes:

This feature should respect the localization/formatting settings given by the user configuration file.

Thank you for considering this request! I believe it would significantly enhance the usability of the application for users in various regions.

**Comment by hargata** [comment] 2024-11-02 14:49
duplicate of #611

**Closed by hargata** 2024-11-02 14:49 UTC
