### ISSUE TITLE
nullref when uploading pdf to service record

### ISSUE THREAD

**Issue by jhofker** [hargata/lubelog#173] opened 2024-01-26 18:13 UTC
Existing service record, attempted to upload a pdf invoice, and got the following error in logs:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
01/26/2024
12:06:38 PM
      An unhandled exception has occurred while executing the request.
01/26/2024
12:06:38 PM
      System.NullReferenceException: Object reference not set to an instance of an object.
01/26/2024
12:06:38 PM
         at CarCareTracker.Controllers.FilesController.HandleMultipleFileUpload(List`1 file) in /App/Controllers/FilesController.cs:line 40
01/26/2024
12:06:38 PM
         at lambda_method250(Closure, Object, Object[])
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
01/26/2024
12:06:38 PM
      --- End of stack trace from previous location ---
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
01/26/2024
12:06:38 PM
      --- End of stack trace from previous location ---
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
01/26/2024
12:06:38 PM
      --- End of stack trace from previous location ---
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
01/26/2024
12:06:38 PM
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by hargata** [comment] 2024-01-26 18:17
what browser? I cannot reproduce this.

**Comment by jhofker** [comment] 2024-01-26 18:22
Sorry, I submitted before I was finished writing 🙃 

- This is in Firefox. 
- The file is definitely large (30MB) and smaller files work. (Why my auto shop generates PDFs that big is a separate issue!)
- The user-facing issue here is that the interface just hangs when this error occurs -- there's no way to close the modal or acknowledge that the upload failed. 

Screenshot:
![image](https://github.com/hargata/lubelog/assets/812787/bc1e2a69-54e7-45ae-a8ed-8876309006c7)

**Comment by hargata** [comment] 2024-01-26 18:46
@jhofker Ahhh alright, so .NET has a default limit of 28.6MB, you can try to put the pdf file in a zip archive as a workaround for now. 
Biggest issue with tryin to increase the limit IMO is that the limit pretty much has to be hardcoded and there's always going to be someone trying to upload a larger file.

**Comment by jhofker** [comment] 2024-01-26 19:18
Yeah agreed -- probably best to just clarify in the UI (at some point) the limits and make sure the error is handled and bubbled back up.

**Comment by hargata** [comment] 2024-01-26 19:45
@jhofker error handling has been added as well as a label that displays the max file size that can be uploaded.

**Comment by hargata** [comment] 2024-01-27 17:59
I'm just going to close this for now. If the user wishes to upload larger files than 28.6MB they can either compress it in an archive or upload it to Google Drive and put the link in the notes.

**Closed by hargata** 2024-01-27 17:59 UTC
