### ISSUE TITLE
[FEATURE REQUEST] New field to the Supplies table for location

### ISSUE THREAD

**Issue by waif69** [hargata/lubelog#392] opened 2024-03-12 17:00 UTC
Could an additional field be added to the Supplies table for Location?

 _It would be preferred over keeping that information in the Notes field. It would also allow a report generation based on location._

**Comment by hargata** [comment] 2024-03-12 17:02
Feature already exists, you can already add custom fields

**Comment by hargata** [comment] 2024-03-12 17:09
Closing this issue as duplicate of #270

**Closed by hargata** 2024-03-12 17:09 UTC
Labels: duplicate
