### ISSUE TITLE
[Feature Request] - Track Insurance Premiums and Inspection Fees

### ISSUE THREAD

**Issue by tetra-archos** [hargata/lubelog#460] opened 2024-04-04 14:47 UTC
A tab to track insurance premiums would be great, especially for places that require insurance and inspections. Maybe relabeling Taxes to Fees, and having multiple Fee types would be a solution?

**Comment by hargata** [comment] 2024-04-04 14:52
This is a duplicate of existing issues, we have looked into it relabeling taxes into fees in the past but it got a lot more complicated once we implemented the translation layer since there are now translations that rely on the key for "Taxes", relabeling it to Fees will break a lot of existing translations. If the wording really bugs you that much, you can create a custom translation that translates Taxes to Fees and it will work.

Multiple fee types is not possible since it will be impossible for us to take into account every single fee type in the world across all the countries, the tagging feature will probably be a better fit for this.

**Closed by hargata** 2024-04-04 14:52 UTC

**Comment by tetra-archos** [comment] 2024-04-04 15:10
That's fair, sorry I didn't realize this was a duplicate, I thought I searched well enough for it.
