### ISSUE TITLE
[Feature Request] Multiple fuels on cars

### ISSUE THREAD

**Issue by lapius** [hargata/lubelog#383] opened 2024-03-09 09:49 UTC
I just found out about this project, looks very interesting. So I decided to migrate from Drivvo app to this one. But there is few issues. My car is going on gasoline (petrol? benzine?) and I have installed LPG (Liquefied petroleum gas). In my Drivvo App, I could select from a lot of fuel types, like Diesel, Electric, Ethanol,  Gasoline, LPG and I could also add my own type. 

Also I could add and choose gas stations where I fueled. I can't find how to add any of that in lubelogger. 

P.S. just thought that gas stations I could add as new field, although it would be better to have a list to choose from. But for fuel consumptions on different fuel tanks to calculate, additional field won't do. 

P.P.S. I am .net full stack (with blazor and MSSQL) developer, so I could try to implement it myself, just need to delve into the code.

**Comment by hargata** [comment] 2024-03-09 14:26
Just use the tagging function

**Comment by hargata** [comment] 2024-03-09 14:31
Marking as duplicate of #34 and #78

**Closed by hargata** 2024-03-09 14:31 UTC
Labels: duplicate

**Comment by lapius** [comment] 2024-03-09 15:06
I would suggest to mention this somewhere in guide, because I was looking everywhere and couldn't find solution. Would be more useful to mention in guide such option. I'm writing this, because I see it's even a duplicate of two issues and a bit confusing.

**Comment by hargata** [comment] 2024-03-23 15:33
thanks, I've updated the documentation to reflect this:

https://docs.lubelogger.com/Records/Fuel%20Records#fuel-mileage-by-tags
