### ISSUE TITLE
[BUG] Decimal separator issue

### ISSUE THREAD

**Issue by redge76** [hargata/lubelog#213] opened 2024-02-02 00:19 UTC
Hi,

If I use the fr_CH or fr_FR locale (with , as decimal separator), I can't add a new gas entry.
It's saved as a "0" value.

If I switch to en_US (with . as separator), it works

Yeah localization is a mess :-(

**Comment by hargata** [comment] 2024-02-02 00:23
which field? using fr_FR I'm able to enter decimals with "," as separator
![image](https://github.com/hargata/lubelog/assets/155338622/39b0ce8a-ffd5-4b2b-90a7-cd1c2fae2ddb)
![image](https://github.com/hargata/lubelog/assets/155338622/50c59c88-7315-46d1-aad9-321f94f37a16)

Version?

**Comment by hargata** [comment] 2024-02-02 01:00
European locale is supported by the app as long as it's configured correctly. Will be closing this issue since it's not a bug.

**Closed** 2024-02-02 01:00 UTC
