### ISSUE TITLE
Visible tabs settings not retained

### ISSUE THREAD

**Issue by mrodus** [hargata/lubelog#561] opened 2024-07-11 10:54 UTC
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

No matter what boxes I check/uncheck under Visible Tabs, in a new session, it always changes back to as shown in the screenshot.

userConfig.json still has the following entry: `"VisibleTabs":[0,8,1]`

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

**Screenshots(optional)**
![image](https://github.com/hargata/lubelog/assets/25194985/fe3aa764-7132-469e-92d3-563b3c7f41b0)

**Comment by hargata** [comment] 2024-07-11 14:40
Cannot reproduce in any environment.

userConfig.json is only updated if you're logged in as the root user or if you don't have any auth set up.

Does other settings persist(dark mode, etc) ?

and what do you mean by "In a new session" ? Are you logging in as a different user?

**Comment by mrodus** [comment] 2024-07-11 16:00
I only have one user and that's set up as an admin.

Yes, other settings persist; it's only happening with the visible tabs.

By a new session, I mean when I open it in an incognito window or after a few days, it seems to be reverted to the default visible tabs selection. (Strangely though, I was doing some tweaking in the userConfig.json file earlier, and now it seems to retain the visible tabs even in an incognito window.)

**Comment by hargata** [comment] 2024-07-11 17:20
@mrodus There is nothing in the code that will overwrite the userConfig.json by itself without any changes from the user, but LubeLogger does cache the user settings in memory after any changes, so the only reason why it would "revert" is if it wasn't able to modify the userConfig.json file in the first place.

Are there any changes to userConfig.json when you change visible tabs?

**Comment by hargata** [comment] 2024-07-11 22:14
We've attempted to reproduce this error in both the Windows standalone and Docker image using the latest version 1.3.5, in both attempts the settings for VisibleTabs is updated in userConfig.json

In the event that this is an issue with LubeLogger temporarily not being able to update the config file for whatever reason(permissions, etc), we recommend that you create a user besides the root user and grant that user admin rights using the admin panel, doing this will allow you side step writing to userConfig.json as the settings for those users are stored in the database.

We'll be closing this issue as "wontfix" since we've stopped investigating and cannot think of any further troubleshooting approach.

**Closed by hargata** 2024-07-11 22:14 UTC
Labels: unreproducible
